Vagrant.configure("2") do |config|
    # Configuration de la première machine virtuelle (Server)
    config.vm.define "kthierryS" do |master|
      master.vm.box = "opensuse/Tumbleweed.x86_64"
      # master.vm.box_version = "2024.04.15.12"
      master.vm.hostname = "kthierryS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.synced_folder ".", "/vagrant"
      master.vm.provider "virtualbox" do |v, override|
        v.gui = true
        v.memory = "1024"
        v.cpus = 1
        v.name = "kthierryS"
      end
      # Provisionnement de la machine virtuelle avec le script
     

      master.vm.provision "shell", path: "./scripts/provision_S.sh", run: "always"
    end
  
    # Configuration de la deuxième machine virtuelle (ServerWorker)
    config.vm.define "kthierrySW" do |node1|
      node1.vm.box = "opensuse/Tumbleweed.x86_64"
      # node1.vm.box_version = "2024.04.15.12"
      node1.vm.hostname = "kthierrySW"
      node1.vm.network "private_network", ip: "192.168.56.111"
      node1.vm.synced_folder ".", "/vagrant"
      node1.vm.provider "virtualbox" do |v, override|
        v.gui = true
        v.memory = "1024"
        v.cpus = 1
        v.name = "kthierrySW"
      end
      # Provisionnement de la machine virtuelle avec le script
     

      node1.vm.provision "shell", path: "./scripts/provision_SW.sh", run: "always"
      
    end
  end
  
