Vagrant.configure("2") do |config|
  config.vm.define "alrusso" do |alrusso|
    alrusso.vm.box = "generic/alpine317"
    alrusso.vm.network "private_network", ip: "192.168.56.110"
    alrusso.vm.synced_folder ".", "/sync"
    # alrusso.vm.provision "ControllerScript", type: "shell", path: "./scripts/Install.sh"
    alrusso.vm.hostname = "alrusso"
    alrusso.vm.provider "virtualbox" do |vb|
      config.vm.network "forwarded_port", guest: 8080, host: 8080
      config.vm.network "forwarded_port", guest: 8888, host: 8888
      vb.name = "alrusso"
      vb.memory = 4096
      vb.cpus = 8
      end
  end
end