Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.hostname = "argo"

  # Utilisation d'une adresse IP statique pour éviter le DHCP
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "argocd"
    vb.memory = "4096"
    vb.cpus = 2
  end


  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Copier les fichiers YAML pour Argo CD dans la VM
  config.vm.provision "file", source: "confs/application.yaml", destination: "/tmp/application.yaml"
  config.vm.provision "file", source: "confs/project.yaml", destination: "/tmp/project.yaml"

  # Exécuter le script d'installation
  config.vm.provision "shell", path: "install.sh", privileged: true, args:["vagrant"]
end
