Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318" # Assurez-vous que cette box correspond à vos besoins
  config.vm.hostname = "argo"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "argocd"
    vb.memory = "4096"
    vb.cpus = 2
  end
  # Copier les fichiers de configuration Argo CD
config.vm.provision "file", source: "confs/application.yaml", destination: "/tmp/application.yaml"
config.vm.provision "file", source: "confs/project.yaml", destination: "/tmp/project.yaml"


  # Passer l'utilisateur 'vagrant' comme argument au script
  config.vm.provision "shell", path: "install.sh", privileged: true, args: ["vagrant"]
end
